//! Build the perf fixture: a ~100k-file repository with a pinned diff series.
//!
//! Run through `fixtures/perf/generate.sh`, which is the committed entry point.
//!
//! The repository is built with `git fast-import` rather than by writing files
//! and running `git add`. That is not only for speed — though a hundred thousand
//! `add`s is minutes and this is seconds — but because fast-import lets every
//! commit's author, committer, and timestamp be stated explicitly. Everything
//! that feeds a commit OID is therefore fixed, so the generated repository has
//! the *same OIDs on every machine*, and `fixtures/perf/expected.toml` can pin
//! them. A fixture whose identity drifts is a fixture whose perf numbers cannot
//! be compared across runs.
//!
//! Usage:
//!   gen_perf_fixture <output-dir> [--print-oids]

use std::io::{BufWriter, Write};
use std::path::{Path, PathBuf};

use andon_core::git::Git;

/// Fixed commit identity. Any change here changes every OID in expected.toml.
const IDENT: &str = "Andon Perf Fixture <perf@andon.invalid> 1767225600 +0000";

fn main() {
    let mut args = std::env::args().skip(1);
    let out = PathBuf::from(args.next().unwrap_or_else(|| usage()));
    let print_oids = args.any(|a| a == "--print-oids");

    let repo_root = repo_root();
    let spec = Spec::load(&repo_root.join("fixtures/perf/series.toml"));

    let repo = out.join("repo");
    if repo.join(".git").is_dir() {
        eprintln!("fixture already present at {}", repo.display());
    } else {
        std::fs::create_dir_all(&repo).expect("create fixture dir");
        build(&repo, &spec);
    }

    let git = Git::open(&repo).expect("fixture is a repository");
    let mut oids: Vec<(String, String)> = vec![("base".to_string(), rev(&git, "refs/heads/base"))];
    for series in &spec.series {
        oids.push((
            series.name.clone(),
            rev(&git, &format!("refs/heads/{}", series.name)),
        ));
    }

    if print_oids {
        println!("# Generated by gen_perf_fixture. See fixtures/perf/series.toml.");
        println!("schema_version = 1");
        println!("[commits]");
        for (name, oid) in &oids {
            println!("{name} = \"{oid}\"");
        }
        return;
    }

    verify(&repo_root.join("fixtures/perf/expected.toml"), &oids);
    checkout_base(&git);
    write_manifest(&out, &spec, &oids);
    println!("fixture ready at {}", repo.display());
}

fn usage() -> ! {
    eprintln!("usage: gen_perf_fixture <output-dir> [--print-oids]");
    std::process::exit(2);
}

/// The andon repository root, found from this crate's manifest.
fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .canonicalize()
        .expect("workspace root")
}

struct Spec {
    seed: u64,
    top_dirs: usize,
    mid_dirs: usize,
    files_per_dir: usize,
    lines_per_file: usize,
    series: Vec<Series>,
    dirty_files: usize,
}

struct Series {
    name: String,
    changed_files: usize,
}

impl Spec {
    fn load(path: &Path) -> Self {
        let text = std::fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        let value: toml::Value = toml::from_str(&text).expect("series.toml parses");
        let layout = &value["layout"];
        let get = |v: &toml::Value, k: &str| v[k].as_integer().expect("integer") as usize;
        Spec {
            seed: value["seed"].as_integer().expect("seed") as u64,
            top_dirs: get(layout, "top_dirs"),
            mid_dirs: get(layout, "mid_dirs"),
            files_per_dir: get(layout, "files_per_dir"),
            lines_per_file: get(layout, "lines_per_file"),
            series: value["series"]
                .as_array()
                .expect("series array")
                .iter()
                .map(|s| Series {
                    name: s["name"].as_str().expect("name").to_string(),
                    changed_files: get(s, "changed_files"),
                })
                .collect(),
            dirty_files: get(&value["dirty"], "files"),
        }
    }

    fn total_files(&self) -> usize {
        self.top_dirs * self.mid_dirs * self.files_per_dir
    }

    fn path_of(&self, index: usize) -> String {
        let per_top = self.mid_dirs * self.files_per_dir;
        let top = index / per_top;
        let rest = index % per_top;
        let mid = rest / self.files_per_dir;
        let file = rest % self.files_per_dir;
        format!("src/p{top:03}/m{mid:03}/f{file:02}.ts")
    }
}

/// A small deterministic PRNG. Not cryptographic and not meant to be: it needs to
/// produce the same bytes on every platform, which rules out anything that might
/// change implementation between releases.
struct Lcg(u64);

impl Lcg {
    fn next(&mut self) -> u64 {
        // Numerical Recipes constants; the low bits are poor, so callers take the
        // high ones.
        self.0 = self
            .0
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        self.0 >> 16
    }
}

/// Plausible TypeScript, generated deterministically.
fn file_body(index: usize, lines: usize, seed: u64, revision: u32) -> Vec<u8> {
    let mut rng =
        Lcg(seed ^ (index as u64).wrapping_mul(0x9E3779B97F4A7C15) ^ (revision as u64) << 32);
    let mut out = String::with_capacity(lines * 48);
    out.push_str("// generated fixture — do not edit\n");
    for line in 0..lines {
        let n = rng.next() % 1000;
        match rng.next() % 4 {
            0 => out.push_str(&format!("export const value{line}_{n} = {n};\n")),
            1 => out.push_str(&format!(
                "export function fn{line}_{n}(a: number): number {{ return a + {n}; }}\n"
            )),
            2 => out.push_str(&format!(
                "export interface Shape{line}_{n} {{ id: number; name: string; }}\n"
            )),
            _ => out.push_str(&format!(
                "if (value{line}_{n} > {n}) {{ console.log('{line}'); }}\n"
            )),
        }
    }
    out.into_bytes()
}

/// Which files a series of the given size touches.
///
/// A fixed stride across the whole tree rather than the first N files: a
/// contiguous change lives in one subtree and lets git's tree walk skip almost
/// everything, which would make the fixture flatter than any real diff.
fn changed_indices(total: usize, count: usize) -> Vec<usize> {
    let stride = (total / count.max(1)).max(1);
    (0..count).map(|i| (i * stride + 7) % total).collect()
}

fn build(repo: &Path, spec: &Spec) {
    let bootstrap = Git::open(Path::new(".")).expect("run from inside a git repository");
    bootstrap
        .cmd(["init", "--quiet", "--initial-branch=base"])
        .arg(repo)
        .output()
        .expect("git init");

    let git = Git::open(repo).expect("fixture repository");
    // fsmonitor and the untracked cache are what make `git status` cheap on a
    // repository this size. They are repository config rather than a pin,
    // because they change how fast git answers and never what it answers — see
    // `PINNED_CONFIG`'s note on why this one is deliberately not pinned.
    for (key, value) in [
        ("core.fsmonitor", "true"),
        ("core.untrackedCache", "true"),
        ("gc.auto", "0"),
        ("maintenance.auto", "false"),
    ] {
        git.cmd(["config", key, value]).output().ok();
    }

    let total = spec.total_files();
    eprintln!("generating {total} files via fast-import...");
    let started = std::time::Instant::now();

    let mut child = git
        .cmd(["fast-import", "--quiet", "--done"])
        .spawn_piped()
        .expect("git fast-import");
    let stdin = child.stdin.take().expect("piped stdin");

    let spec_seed = spec.seed;
    let lines = spec.lines_per_file;
    let paths: Vec<String> = (0..total).map(|i| spec.path_of(i)).collect();
    let series: Vec<(String, Vec<usize>)> = spec
        .series
        .iter()
        .map(|s| (s.name.clone(), changed_indices(total, s.changed_files)))
        .collect();

    let writer = std::thread::spawn(move || {
        let mut out = BufWriter::with_capacity(1 << 20, stdin);
        // Blobs first, each with a mark the commits refer to.
        for (i, _) in paths.iter().enumerate() {
            let body = file_body(i, lines, spec_seed, 0);
            write!(out, "blob\nmark :{}\ndata {}\n", i + 1, body.len()).unwrap();
            out.write_all(&body).unwrap();
            out.write_all(b"\n").unwrap();
        }
        // The base commit names every file.
        write!(
            out,
            "commit refs/heads/base\nmark :{}\nauthor {IDENT}\ncommitter {IDENT}\ndata 4\nbase\n",
            total + 1
        )
        .unwrap();
        for (i, path) in paths.iter().enumerate() {
            writeln!(out, "M 100644 :{} {}", i + 1, path).unwrap();
        }
        out.write_all(b"\n").unwrap();

        // Each series is a branch off base carrying only its own edits.
        let mut mark = total + 2;
        for (name, indices) in &series {
            let mut blobs = Vec::with_capacity(indices.len());
            for index in indices {
                let body = file_body(*index, lines, spec_seed, 1);
                write!(out, "blob\nmark :{mark}\ndata {}\n", body.len()).unwrap();
                out.write_all(&body).unwrap();
                out.write_all(b"\n").unwrap();
                blobs.push((mark, *index));
                mark += 1;
            }
            write!(
                out,
                "commit refs/heads/{name}\nmark :{mark}\nauthor {IDENT}\ncommitter {IDENT}\ndata {}\n{name}\n",
                name.len()
            )
            .unwrap();
            writeln!(out, "from :{}", total + 1).unwrap();
            for (blob_mark, index) in blobs {
                writeln!(out, "M 100644 :{blob_mark} {}", paths[index]).unwrap();
            }
            out.write_all(b"\n").unwrap();
            mark += 1;
        }
        out.write_all(b"done\n").unwrap();
        out.flush().unwrap();
    });

    let output = child.wait_with_output().expect("fast-import runs");
    writer.join().expect("stream writer");
    assert!(
        output.status.success(),
        "fast-import failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    eprintln!("fast-import done in {:?}", started.elapsed());
}

fn checkout_base(git: &Git) {
    // fast-import populates the object database and the refs but leaves the
    // index and working tree empty. The dirty-tree measurement needs both.
    if git.workdir().join("src").is_dir() {
        return;
    }
    eprintln!("checking out base...");
    let started = std::time::Instant::now();
    git.cmd(["checkout", "--quiet", "--force", "base"])
        .output()
        .expect("checkout base");
    eprintln!("checkout done in {:?}", started.elapsed());
}

fn rev(git: &Git, refname: &str) -> String {
    git.cmd(["rev-parse", refname])
        .text()
        .unwrap_or_else(|e| panic!("rev-parse {refname}: {e}"))
        .trim()
        .to_string()
}

/// Write what the harness needs to know, so it does not re-parse `series.toml`.
///
/// Two readers of one spec drift, and they drift silently: the harness would
/// keep measuring while disagreeing with the generator about which files are
/// supposed to be dirty. One producer, one manifest, no second interpretation.
fn write_manifest(out: &Path, spec: &Spec, oids: &[(String, String)]) {
    let dirty: Vec<String> = changed_indices(spec.total_files(), spec.dirty_files)
        .into_iter()
        .map(|i| spec.path_of(i))
        .collect();
    let mut json = String::from("{\n  \"commits\": {\n");
    for (i, (name, oid)) in oids.iter().enumerate() {
        let comma = if i + 1 == oids.len() { "" } else { "," };
        json.push_str(&format!("    \"{name}\": \"{oid}\"{comma}\n"));
    }
    json.push_str("  },\n  \"dirty_paths\": [\n");
    for (i, path) in dirty.iter().enumerate() {
        let comma = if i + 1 == dirty.len() { "" } else { "," };
        json.push_str(&format!("    \"{path}\"{comma}\n"));
    }
    json.push_str("  ]\n}\n");
    std::fs::write(out.join("fixture.json"), json).expect("write manifest");
}

/// Compare against the committed pins, and say plainly what to do if they differ.
fn verify(expected_path: &Path, actual: &[(String, String)]) {
    let text = std::fs::read_to_string(expected_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", expected_path.display()));
    let value: toml::Value = toml::from_str(&text).expect("expected.toml parses");
    let commits = &value["commits"];
    let mut wrong = Vec::new();
    for (name, oid) in actual {
        let pinned = commits[name.as_str()].as_str().expect("pinned oid");
        if pinned != oid {
            wrong.push(format!("{name}: expected {pinned}, generated {oid}"));
        }
    }
    assert!(
        wrong.is_empty(),
        "the generated fixture does not match its pins:\n  {}\n\n\
         The fixture defines what the perf numbers are numbers *about*, so a \
         drift here invalidates every comparison against a previous run. If the \
         change to series.toml was deliberate, regenerate the pins with \
         --print-oids and ledger the budget implications.",
        wrong.join("\n  ")
    );
}
